Features/in 5
FedAGcom/Internship pull request #4
Opened 2022-05-30 12:50 UTC by IlyaKayrachka

Сущность User

2022-05-31 07:33 UTC, FedorGODUS requested changes

2022-06-01 12:00 UTC, Aleksandr-Gurin requested changes

2022-06-01 12:00 UTC, Aleksandr-Gurin commented on src/main/java/com/fedag/internship/controller/UserController.java
> +                .orElseThrow();
Думаю Optional здесь особо не нужен, можно оставить
UserDto userDto = userMapper.toDto(userService.getUserById(id))

2022-06-01 12:00 UTC, Aleksandr-Gurin commented on src/main/java/com/fedag/internship/controller/UserController.java
> +                .map(userMapper::toDto);
Думаю лучше использовать pageable и аннотацию @PageableDefault, пример можно глянуть здесь: https://www.baeldung.com/spring-data-web-support

2022-06-01 12:00 UTC, Aleksandr-Gurin commented on src/main/java/com/fedag/internship/controller/UserController.java
> +                .map(userService::editUser);
Optional избыточен

2022-06-04 14:33 UTC, merged